### ISSUE TITLE
API-Gateway routing issue on /api/gateway

### ISSUE THREAD

**Issue by ezYakaEagle442** [ezYakaEagle442/aca-java-petclinic-mic-srv#1]
On ASA, the routing is fine, see [https://asa-petcliasa-api-gateway.azuremicroservices.io](https://asa-petcliasa-api-gateway.azuremicroservices.io)/ , all works fine.

on ACA, the routing works partially , I have successfully added one new owner but then I fail to [edit](https://aca-petcliaca-api-gateway--4ahxiuy.bluepebble-754d2322.francecentral.azurecontainerapps.io/#!/owners/details/11) it : 
- I can see this error on the browser console : {"timestamp":"2022-10-31T10:35:52.177+00:00","path":"/api/gateway/owners/11","status":500,"error":"Internal Server Error","requestId":"9d84b387-3027"}
- I see the above URL from the [owner-details.controller.js](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/spring-petclinic-api-gateway/src/main/resources/static/scripts/owner-details/owner-details.controller.js) , the  /api/gateway routing rule is not defined in the[Spring Cloud gateway config ](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/spring-petclinic-api-gateway/src/main/resources/application.yml) but in the [ApiGatewayController](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/boundary/web/ApiGatewayController.java#L39).

-I have also updated the URL : 
  -https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/application/CustomersServiceClient.java#L36
  - https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/application/VisitsServiceClient.java#L36

10/31/2022, 10:54:39.362 AM
2022-10-31 10:54:37.310 ERROR 1 --- [or-http-epoll-3] a.w.r.e.AbstractErrorWebExceptionHandler : [4c7a21bd-3073] 500 Server Error for HTTP GET "**/api/gateway/owners/11**"
10/31/2022, 10:54:39.362 AM
Error has been observed at the following site(s):
10/31/2022, 10:54:39.362 AM
*__checkpoint ⇢ Request to GET http://customers-service/owners/11 [DefaultWebClient]
10/31/2022, 10:54:39.362 AM
*__checkpoint ⇢ Handler org.springframework.samples.petclinic.api.boundary.web.ApiGatewayController#getOwnerDetails(int) [DispatcherHandler]
10/31/2022, 10:54:39.362 AM
*__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
10/31/2022, 10:54:39.362 AM
*__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
10/31/2022, 10:54:39.362 AM
*__checkpoint ⇢ HTTP GET "/api/gateway/owners/11" [ExceptionHandlingWebHandler]

**Comment by ezYakaEagle442** [comment]
Note: the Zuul routing had been removed , I doubt this would be the root cause as it had also been removed in the [ASA Config](https://github.com/ezYakaEagle442/spring-petclinic-microservices-config)
 see :
- [https://github.com/spring-petclinic/spring-petclinic-microservices-config/blob/main/api-gateway.yml#L8](https://github.com/spring-petclinic/spring-petclinic-microservices-config/blob/main/api-gateway.yml#L8) & 
- [https://github.com/Azure-Samples/spring-petclinic-microservices-config/blob/master/api-gateway.yml](https://github.com/Azure-Samples/spring-petclinic-microservices-config/blob/master/api-gateway.yml)

The difference is that the ApiGatewayController [in ACA ](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/boundary/web/ApiGatewayController.java#L40) does not use the Eureka discovery server, whereas it does with [ASA]() :
```sh
@EnableDiscoveryClient
@SpringBootApplication
public class ApiGatewayApplication {
```


See also the [Spring Cloud Gateway Config with ASA](https://github.com/ezYakaEagle442/azure-spring-apps-petclinic-mic-srv/blob/azure/spring-petclinic-api-gateway/src/main/resources/application.yml#L6) :
 
```sh
spring:
  cloud:
    gateway:
      discovery:
        # make sure a DiscoveryClient implementation (such as Netflix Eureka) is on the classpath and enabled
        locator: # https://cloud.spring.io/spring-cloud-gateway/reference/html/#the-discoveryclient-route-definition-locator
          enabled: true #  to configure Spring Cloud Gateway to use the Spring Cloud Service Registry to discover the available microservices.    
      routes:
        - id: vets-service
          uri: http://vets-service
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: http://visits-service
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: http://customers-service
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
      globalcors: # o allow CORS requests to our gateway. This can be helpful when you add a front-end that is not hosted on Azure Spring Apps.
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET    
```

**Comment by ezYakaEagle442** [comment]
anothe difference is that the [CircuitBreaker was removed in ACA](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/boundary/web/ApiGatewayController.java#L50) :

```sh
    @GetMapping(value = "owners/{ownerId}")
    public Mono<OwnerDetails> getOwnerDetails(final @PathVariable int ownerId) {
        return customersServiceClient.getOwner(ownerId)
            .flatMap(owner ->
                visitsServiceClient.getVisitsForPets(owner.getPetIds())
                    .transform(it -> {
                        ReactiveCircuitBreaker cb = cbFactory.create("getOwnerDetails");
                        return cb.run(it, throwable -> emptyVisitsForPets());
                    })
                    .map(addVisitsToOwner(owner))
            );

    }
```

compared to the original Petclinic , kept as such in my [ASA versioin](https://github.com/ezYakaEagle442/azure-spring-apps-petclinic-mic-srv/blob/azure/spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/boundary/web/ApiGatewayController.java#L54)

```sh

    @GetMapping(value = "owners/{ownerId}")
    public Mono<OwnerDetails> getOwnerDetails(final @PathVariable int ownerId) {
        return customersServiceClient.getOwner(ownerId)
            .flatMap(owner ->
                visitsServiceClient.getVisitsForPets(owner.getPetIds())
                    .transform(it -> {
                        ReactiveCircuitBreaker cb = cbFactory.create("getOwnerDetails");
                        return cb.run(it, throwable -> emptyVisitsForPets());
                    })
                    .map(addVisitsToOwner(owner))
            );

    }
```

**Comment by rambotzhong** [comment]
hi @ezYakaEagle442,  can you get any error message from customers service? And how do you setting the property 'CUSTOMERS_SVC_URL' ?

**Comment by ezYakaEagle442** [comment]
Hi @rambotzhong I think there is no error message from customer-service because the resuest is not routed to it.
CUSTOMERS_SVC_URL is correctly set in [Bicep](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/iac/bicep/modules/aca/apps/aca-ui.bicep#L236) , I have checked then in the Azure portal.

**Comment by rambotzhong** [comment]
> Hi @rambotzhong I think there is no error message from customer-service because the resuest is not routed to it. CUSTOMERS_SVC_URL is correctly set in [Bicep](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/iac/bicep/modules/aca/apps/aca-ui.bicep#L236) , I have checked then in the Azure portal.

Thanks. I tried to run your applaction locally, the uri can not be constructed by environment variables when you construct the [webclient](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/6f2e2c478644caffac4635c034153698e777a09f/spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/application/CustomersServiceClient.java#L36). Maybe you can use @Value to read from Spring properties.

**Comment by ezYakaEagle442** [comment]
@rambotzhong why the uri can not be constructed by environment variables when you construct the [webclient](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/6f2e2c478644caffac4635c034153698e777a09f/spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/application/CustomersServiceClient.java#L36) ?

**Comment by rambotzhong** [comment]
> @rambotzhong why the uri can not be constructed by environment variables when you construct the [webclient](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/6f2e2c478644caffac4635c034153698e777a09f/spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/application/CustomersServiceClient.java#L36) ?

The UriBuilder does not support inject environment variable to the uri directly. You can get the value by [spring value injection](https://www.baeldung.com/spring-boot-properties-env-variables).

**Comment by ezYakaEagle442** [comment]
Indeed I understand now, see [https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config )

**Comment by ezYakaEagle442** [comment]
@rambotzhong I did update the code [https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/application/CustomersServiceClient.java](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/spring-petclinic-api-gateway/src/main/java/org/springframework/samples/petclinic/api/application/CustomersServiceClient.java) but the App fails to start,  hit this error :

```sh
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customersServiceClient' defined in file [/tmp/app/BOOT-INF/classes/org/springframework/samples/petclinic/api/application/CustomersServiceClient.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.samples.petclinic.api.application.CustomersServiceClient]: Constructor threw exception; nested exception is java.lang.NullPointerException
```

This was the guilty snippet  but why ?:
```sh
 String CONTAINER_APP_ENV_DNS_SUFFIX = environment.getProperty("container.app.env.dns.suffix");
 String CUSTOMERS_SVC_URL = environment.getProperty("customers.svc.url");
 ```

**Comment by ezYakaEagle442** [comment]
@rambotzhong  Then I hit
```console
java.net.UnknownHostException: Failed to resolve 'customers-service.internal.null' after 2 queries
```

Important note : ${container.app.env.dns.suffix} is an Env. var auto-injected in the ACA Container, it is NOT a property set anywhere in a Spring Property.

my snippet looks like this
```sh
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.env.Environment;

@Component
@RequiredArgsConstructor
public class CustomersServiceClient {

    private final WebClient.Builder webClientBuilder;

    @Value("${container.app.env.dns.suffix}")
    private String acaEnvDnsSuffix;

    @Value("${customers.svc.url}")
    private String customersServiceUrl;

    @Autowired
    private Environment environment;

    //String CONTAINER_APP_ENV_DNS_SUFFIX = environment.getProperty("container.app.env.dns.suffix");
    //String CUSTOMERS_SVC_URL = environment.getProperty("customers.svc.url");

    String internalK8Ssvc2svcRoute = "http://customers-service.internal." + acaEnvDnsSuffix;

    public Mono<OwnerDetails> getOwner(final int ownerId) {

        System.out.println("Checking ALL ENV variable  : |" + "|\n");
		System.getenv().forEach((key, value) -> {
			System.out.println(key + ":" + value);
		});

		System.out.println("Checking ALL ENV Properties  : |" + "|\n");
		System.getProperties().forEach((key, value) -> {
			System.out.println(key + ":" + value);
		});
        
        return webClientBuilder.build().get()
            .uri(internalK8Ssvc2svcRoute + "/owners/{ownerId}", ownerId)
            .retrieve()
            .bodyToMono(OwnerDetails.class);
    }
}

```



```console
Checking ALL ENV variable  : 
CONTAINER_APP_HOSTNAME:aca-petcliaca-api-gateway--jnd6baq.bluepebble-754d2322.francecentral.azurecontainerapps.io
CONTAINER_APP_NAME:aca-petcliaca-api-gateway
CONTAINER_APP_REVISION:aca-petcliaca-api-gateway--jnd6baq
CONTAINER_APP_ENV_DNS_SUFFIX:bluepebble-754d2322.francecentral.azurecontainerapps.io
```

**Comment by ezYakaEagle442** [comment]
finally fixed with:

```sh
String internalK8Ssvc2svcRoute = "http://" + System.getenv("CUSTOMERS_SVC_APP_NAME") + ".internal." + System.getenv("CONTAINER_APP_ENV_DNS_SUFFIX");
```
